### ISSUE TITLE
Crash with Portable Miner

### ISSUE THREAD

**Issue by N-Montana** [oukibt/ResourceNodeRandomizer#2]
I've been getting a strange crash when using the mod. Whenever I place a portable miner on a randomized node then save and reload trying to open the miner instantly crashes the game. I've been able to confirm that creating a new world with only this mod and repeating the steps causes the crash.

The error the game gives is:

Version: 372858, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Standalone, IsUsingMods: Yes, IsSaveGameEdited: No

Assertion failed: mResourceClass [File:C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Source\FactoryGame\Private\Resources\FGResourceNode.cpp] [Line: 229]

FactoryGameSteam_FactoryGame_Win64_Shipping!AFGResourceNode::GetExtractionSpeedMultiplier() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Source\FactoryGame\Private\Resources\FGResourceNode.cpp:229]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGResourceNodeBase::execGetExtractionSpeedMultiplier() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Intermediate\Build\Win64\FactoryGameSteam\Inc\FactoryGame\UHT\FGResourceNodeBase.gen.cpp:226]
FactoryGameSteam_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6666]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::CallFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1156]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessContextOpcode() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3110]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::execLet() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2852]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1225]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1055]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3241]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1225]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1323]
FactoryGameSteam_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6666]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2161]
FactoryGameSteam_UMG_Win64_Shipping!UUserWidget::NativeConstruct() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\UMG\Private\UserWidget.cpp:1515]
FactoryGameSteam_FactoryGame_Win64_Shipping!UFGUserWidget::NativeConstruct() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Source\FactoryGame\Private\UI\FGUserWidget.cpp:36]
FactoryGameSteam_FactoryGame_Win64_Shipping!UFGInteractWidget::NativeConstruct() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Source\FactoryGame\Private\UI\FGInteractWidget.cpp:40]
FactoryGameSteam_UMG_Win64_Shipping!UWidget::TakeWidget_Private() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\UMG\Private\Components\Widget.cpp:1036]
FactoryGameSteam_UMG_Win64_Shipping!UHorizontalBoxSlot::BuildSlot() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\UMG\Private\Components\HorizontalBoxSlot.cpp:33]
FactoryGameSteam_UMG_Win64_Shipping!UHorizontalBox::OnSlotAdded() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\UMG\Private\Components\HorizontalBox.cpp:37]
FactoryGameSteam_UMG_Win64_Shipping!UPanelWidget::execAddChild() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Intermediate\Build\Win64\FactoryGameSteam\Inc\UMG\UHT\PanelWidget.gen.cpp:46]
FactoryGameSteam_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6666]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::CallFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1156]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessContextOpcode() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3110]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::execLetObj() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2898]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1225]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1055]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3241]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1225]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1055]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::execLocalVirtualFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3234]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessContextOpcode() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3110]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1225]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1055]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3241]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1225]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1323]
FactoryGameSteam_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6666]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2161]
FactoryGameSteam_Engine_Win64_Shipping!AActor::ProcessEvent() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:1175]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGHUD::OpenInteractUI() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Intermediate\Build\Win64\FactoryGameSteam\Inc\FactoryGame\UHT\FGHUD.gen.cpp:958]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGPortableMiner::OnUse_Implementation() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Source\FactoryGame\Private\FGPortableMiner.cpp:267]
FactoryGameSteam_FactoryGame_Win64_Shipping!IFGUseableInterface::execOnUse() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Intermediate\Build\Win64\FactoryGameSteam\Inc\FactoryGame\UHT\FGUseableInterface.gen.cpp:408]
FactoryGameSteam_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6666]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2161]
FactoryGameSteam_Engine_Win64_Shipping!AActor::ProcessEvent() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:1175]
FactoryGameSteam_FactoryGame_Win64_Shipping!IFGUseableInterface::Execute_OnUse() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Intermediate\Build\Win64\FactoryGameSteam\Inc\FactoryGame\UHT\FGUseableInterface.gen.cpp:1067]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGCharacterPlayer::OnUse() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Source\FactoryGame\Private\FGCharacterPlayer.cpp:2945]
FactoryGameSteam_FactoryGame_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,AFGBuildableLightSource,void __cdecl(UFGPowerInfoComponent *),FDefaultDelegateUserPolicy>::Execute() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:650]
FactoryGameSteam_FactoryGame_Win64_Shipping!FEnhancedInputActionEventDelegateBinding<TDelegate<void __cdecl(FInputActionValue const &),FDefaultDelegateUserPolicy> >::Execute() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Plugins\EnhancedInput\Source\EnhancedInput\Public\EnhancedInputComponent.h:300]
FactoryGameSteam_EnhancedInput_Win64_Shipping!UEnhancedPlayerInput::EvaluateInputDelegates() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Plugins\EnhancedInput\Source\EnhancedInput\Private\EnhancedPlayerInput.cpp:592]
FactoryGameSteam_Engine_Win64_Shipping!UPlayerInput::ProcessInputStack() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\UserInterface\PlayerInput.cpp:1133]
FactoryGameSteam_FactoryGame_Win64_Shipping!UFGPlayerInput::ProcessInputStack() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Source\FactoryGame\Private\FGPlayerInput.cpp:116]
FactoryGameSteam_Engine_Win64_Shipping!APlayerController::ProcessPlayerInput() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:2690]
FactoryGameSteam_Engine_Win64_Shipping!APlayerController::TickPlayerInput() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:4966]
FactoryGameSteam_Engine_Win64_Shipping!APlayerController::PlayerTick() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:2291]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGPlayerController::PlayerTick() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Source\FactoryGame\Private\FGPlayerController.cpp:478]
FactoryGameSteam_Engine_Win64_Shipping!APlayerController::TickActor() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\PlayerController.cpp:5126]
FactoryGameSteam_Engine_Win64_Shipping!FActorTickFunction::ExecuteTick() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:254]
FactoryGameSteam_Engine_Win64_Shipping!FTickFunctionTask::DoTask() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:280]
FactoryGameSteam_Engine_Win64_Shipping!TGraphTask<FTickFunctionTask>::ExecuteTask() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:1270]
FactoryGameSteam_Core_Win64_Shipping!FNamedTaskThread::ProcessTasksUntilQuit() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:648]
FactoryGameSteam_Core_Win64_Shipping!FTaskGraphCompatibilityImplementation::WaitUntilTasksComplete() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:2125]
FactoryGameSteam_Engine_Win64_Shipping!FTickTaskSequencer::ReleaseTickGroup() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:545]
FactoryGameSteam_Engine_Win64_Shipping!FTickTaskManager::RunTickGroup() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:1595]
FactoryGameSteam_Engine_Win64_Shipping!UWorld::Tick() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:1521]
FactoryGameSteam_Engine_Win64_Shipping!UGameEngine::Tick() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Engine\Private\GameEngine.cpp:1796]
FactoryGameSteam_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [C:\BuildAgent\work\b731a33f2a691e17\UE4\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:15]
FactoryGameSteam_Win64_Shipping!FEngineLoop::Tick() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5864]
FactoryGameSteam_Win64_Shipping!GuardedMain() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:188]
FactoryGameSteam_Win64_Shipping!GuardedMainWrapper() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:118]
FactoryGameSteam_Win64_Shipping!LaunchWindowsStartup() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:258]
FactoryGameSteam_Win64_Shipping!WinMain() [C:\BuildAgent\work\b731a33f2a691e17\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:298]
FactoryGameSteam_Win64_Shipping!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by oukibt** [comment]
Sorry for the delay, the crash has been fixed in the new version (0.1.3). Thanks for your feedback!
