### ISSUE TITLE
Shuffled Ores tend to be placed far from surface

### ISSUE THREAD

**Issue by ShinryuAspect** [oukibt/ResourceNodeRandomizer#3]
I've found from time to time nodes sticking way too far out from the surface. I assume that has something to do with the shuffled ore height being higher than the original location or something along those lines. Could it be possible to update the height from the shuffled node to be equal or similar to the replaced?

Image for reference:
![20241104114436_1](https://github.com/user-attachments/assets/7a1cfe48-b6df-4dd5-90c0-0a518561b00b)

**Comment by oukibt** [comment]
Yep, it's known and weird issue. I prefer to do multiplayer support first
